name: Continuous Integration

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    client:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: client

            steps:
                - name: Check out repo
                  uses: actions/checkout@v2

                - name: Setup Node.js
                  uses: actions/setup-node@v1
                  with:
                      node-version: 12.x

                - name: Install npm dependencies
                  run: npm ci

                - name: Prettier Formatting Check
                  run: npm run prettier:check

                - name: Build React App
                  run: npm run build

    server:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: server
        steps:
            - name: Check out repo
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install npm dependencies
              run: npm ci

            - name: Prettier Formatting Check
              run: npm run prettier:check

            - name: Build TypeScript Project
              run: npm run build
